//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_Type
    {
        public Apply_Type()
        {
            this.Apply_jiludan = new HashSet<Apply_jiludan>();
        }
    
        public int AttendanceID { get; set; }
        public string AttendanceName { get; set; }
    
        public virtual ICollection<Apply_jiludan> Apply_jiludan { get; set; }
    }
}
