//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HrmDBEntities3 : DbContext
    {
        public HrmDBEntities3()
            : base("name=HrmDBEntities3")
        {
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Apply_jiludan> Apply_jiludan { get; set; }
        public DbSet<Apply_Type> Apply_Type { get; set; }
        public DbSet<Chuchai> Chuchai { get; set; }
        public DbSet<Dept_bumen> Dept_bumen { get; set; }
        public DbSet<Module_quanxian> Module_quanxian { get; set; }
        public DbSet<Role_juese> Role_juese { get; set; }
        public DbSet<Tiaoxiu> Tiaoxiu { get; set; }
        public DbSet<User_YG> User_YG { get; set; }
        public DbSet<Waiqing> Waiqing { get; set; }
        public DbSet<View_Chuchai> View_Chuchai { get; set; }
        public DbSet<View_QJlist> View_QJlist { get; set; }
        public DbSet<View_Tiaoxiu> View_Tiaoxiu { get; set; }
        public DbSet<View_Waiqin> View_Waiqin { get; set; }
        public DbSet<View_YG> View_YG { get; set; }
        public DbSet<qiandao> qiandao { get; set; }
    
        public virtual int proc_add_chuchai(string name, string dizhi, string liyou, Nullable<System.DateTime> time1, Nullable<System.DateTime> time2, string jieguo, string zhichi, string shenghe, string shenghe2)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dizhiParameter = dizhi != null ?
                new ObjectParameter("dizhi", dizhi) :
                new ObjectParameter("dizhi", typeof(string));
    
            var liyouParameter = liyou != null ?
                new ObjectParameter("liyou", liyou) :
                new ObjectParameter("liyou", typeof(string));
    
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            var jieguoParameter = jieguo != null ?
                new ObjectParameter("jieguo", jieguo) :
                new ObjectParameter("jieguo", typeof(string));
    
            var zhichiParameter = zhichi != null ?
                new ObjectParameter("zhichi", zhichi) :
                new ObjectParameter("zhichi", typeof(string));
    
            var shengheParameter = shenghe != null ?
                new ObjectParameter("shenghe", shenghe) :
                new ObjectParameter("shenghe", typeof(string));
    
            var shenghe2Parameter = shenghe2 != null ?
                new ObjectParameter("shenghe2", shenghe2) :
                new ObjectParameter("shenghe2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_add_chuchai", nameParameter, dizhiParameter, liyouParameter, time1Parameter, time2Parameter, jieguoParameter, zhichiParameter, shengheParameter, shenghe2Parameter);
        }
    
        public virtual int proc_add_qj(string name, Nullable<int> leixngid, Nullable<System.DateTime> time1, Nullable<System.DateTime> time2, string qjsy, string qjtype, string shenghe, string shenghe2)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var leixngidParameter = leixngid.HasValue ?
                new ObjectParameter("leixngid", leixngid) :
                new ObjectParameter("leixngid", typeof(int));
    
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            var qjsyParameter = qjsy != null ?
                new ObjectParameter("qjsy", qjsy) :
                new ObjectParameter("qjsy", typeof(string));
    
            var qjtypeParameter = qjtype != null ?
                new ObjectParameter("qjtype", qjtype) :
                new ObjectParameter("qjtype", typeof(string));
    
            var shengheParameter = shenghe != null ?
                new ObjectParameter("shenghe", shenghe) :
                new ObjectParameter("shenghe", typeof(string));
    
            var shenghe2Parameter = shenghe2 != null ?
                new ObjectParameter("shenghe2", shenghe2) :
                new ObjectParameter("shenghe2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_add_qj", nameParameter, leixngidParameter, time1Parameter, time2Parameter, qjsyParameter, qjtypeParameter, shengheParameter, shenghe2Parameter);
        }
    
        public virtual int proc_add_tiaoxiu(string name, Nullable<System.DateTime> time1, Nullable<System.DateTime> time2, string anpai, string shenghe, string shenghe2)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            var anpaiParameter = anpai != null ?
                new ObjectParameter("anpai", anpai) :
                new ObjectParameter("anpai", typeof(string));
    
            var shengheParameter = shenghe != null ?
                new ObjectParameter("shenghe", shenghe) :
                new ObjectParameter("shenghe", typeof(string));
    
            var shenghe2Parameter = shenghe2 != null ?
                new ObjectParameter("shenghe2", shenghe2) :
                new ObjectParameter("shenghe2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_add_tiaoxiu", nameParameter, time1Parameter, time2Parameter, anpaiParameter, shengheParameter, shenghe2Parameter);
        }
    
        public virtual int proc_add_waiqin(string name, Nullable<System.DateTime> time1, Nullable<System.DateTime> time2, string dizhi, string liyou, string shenghe, string shenghe2)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            var dizhiParameter = dizhi != null ?
                new ObjectParameter("dizhi", dizhi) :
                new ObjectParameter("dizhi", typeof(string));
    
            var liyouParameter = liyou != null ?
                new ObjectParameter("liyou", liyou) :
                new ObjectParameter("liyou", typeof(string));
    
            var shengheParameter = shenghe != null ?
                new ObjectParameter("shenghe", shenghe) :
                new ObjectParameter("shenghe", typeof(string));
    
            var shenghe2Parameter = shenghe2 != null ?
                new ObjectParameter("shenghe2", shenghe2) :
                new ObjectParameter("shenghe2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_add_waiqin", nameParameter, time1Parameter, time2Parameter, dizhiParameter, liyouParameter, shengheParameter, shenghe2Parameter);
        }
    
        public virtual int proc_select_qj(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_select_qj", nameParameter);
        }
    
        public virtual int proc_update_mima(string uname, string newpwd, string hd1)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var newpwdParameter = newpwd != null ?
                new ObjectParameter("newpwd", newpwd) :
                new ObjectParameter("newpwd", typeof(string));
    
            var hd1Parameter = hd1 != null ?
                new ObjectParameter("hd1", hd1) :
                new ObjectParameter("hd1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_update_mima", unameParameter, newpwdParameter, hd1Parameter);
        }
    
        public virtual int proc_update_yg(Nullable<int> gonghao, string name, Nullable<int> roid, string sex, Nullable<int> bumenid, Nullable<int> age, string xueli, string pwd, string idshenf, Nullable<decimal> gongzi, string mibaowenti, string mibaopwd, Nullable<int> id)
        {
            var gonghaoParameter = gonghao.HasValue ?
                new ObjectParameter("gonghao", gonghao) :
                new ObjectParameter("gonghao", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var roidParameter = roid.HasValue ?
                new ObjectParameter("roid", roid) :
                new ObjectParameter("roid", typeof(int));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var bumenidParameter = bumenid.HasValue ?
                new ObjectParameter("bumenid", bumenid) :
                new ObjectParameter("bumenid", typeof(int));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var xueliParameter = xueli != null ?
                new ObjectParameter("xueli", xueli) :
                new ObjectParameter("xueli", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var idshenfParameter = idshenf != null ?
                new ObjectParameter("idshenf", idshenf) :
                new ObjectParameter("idshenf", typeof(string));
    
            var gongziParameter = gongzi.HasValue ?
                new ObjectParameter("gongzi", gongzi) :
                new ObjectParameter("gongzi", typeof(decimal));
    
            var mibaowentiParameter = mibaowenti != null ?
                new ObjectParameter("mibaowenti", mibaowenti) :
                new ObjectParameter("mibaowenti", typeof(string));
    
            var mibaopwdParameter = mibaopwd != null ?
                new ObjectParameter("mibaopwd", mibaopwd) :
                new ObjectParameter("mibaopwd", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_update_yg", gonghaoParameter, nameParameter, roidParameter, sexParameter, bumenidParameter, ageParameter, xueliParameter, pwdParameter, idshenfParameter, gongziParameter, mibaowentiParameter, mibaopwdParameter, idParameter);
        }
    }
}
