//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_quanxian
    {
        public Module_quanxian()
        {
            this.Module_quanxian1 = new HashSet<Module_quanxian>();
            this.Role_juese = new HashSet<Role_juese>();
        }
    
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual ICollection<Module_quanxian> Module_quanxian1 { get; set; }
        public virtual Module_quanxian Module_quanxian2 { get; set; }
        public virtual ICollection<Role_juese> Role_juese { get; set; }
    }
}
