//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qiandao
    {
        public int QDid { get; set; }
        public string QDtitle { get; set; }
        public string QDZ { get; set; }
        public Nullable<System.DateTime> QDtime { get; set; }
        public Nullable<bool> QDstate { get; set; }
        public string FQQDZ { get; set; }
        public string shijian
        {
            get
            {
                return QDtime.ToString();

            }
        }
    }
}
