//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_juese
    {
        public Role_juese()
        {
            this.User_YG = new HashSet<User_YG>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public int ModuleID { get; set; }
    
        public virtual Module_quanxian Module_quanxian { get; set; }
        public virtual ICollection<User_YG> User_YG { get; set; }
    }
}
