//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_YG
    {
        public int UserID { get; set; }
        public int GhaoID { get; set; }
        public string UserName { get; set; }
        public int RoleID { get; set; }
        public int DeptID { get; set; }
        public string UserPwd { get; set; }
        public string IDCar { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public System.DateTime Starttime { get; set; }
        public string Time
        {
            get { return Starttime.ToString("yyyy-MM-dd HH:mm:ss"); }
        }

      
        public string Education { get; set; }
        public decimal Salary { get; set; }
        public string mibaowenti { get; set; }
        public string mimapwd { get; set; }
        public string RoleName { get; set; }
        public string DeptName { get; set; }
    }
}
